export const productTypes = {
	0: {
		id: '0',
		lable: '特卖商品',
	},
	1: {
		id: '1',
		lable: '虚拟商品',
	},
};

export const boutiqueSkuTpl = [
	{
		cost: 0,
		color: 'Associate-经理券',
		propertiesName: 'Associate-经理券',
		agentPrice: 0,
		supplierSkucode: '',
		remainNum: 10000,
		picPath: '',
		stdSalePrice: 0,
		propertiesAlias: 'Associate-经理券',
	},
	{
		cost: 0,
		color: 'Director-主管券',
		propertiesName: 'Director-主管券',
		agentPrice: 0,
		supplierSkucode: '',
		remainNum: 10000,
		picPath: '',
		stdSalePrice: 0,
		propertiesAlias: 'Director-主管券',
	},
	{
		cost: 0,
		color: 'Partner-合伙人券',
		propertiesName: 'Partner-合伙人券',
		agentPrice: 0,
		supplierSkucode: '',
		remainNum: 10000,
		picPath: '',
		stdSalePrice: 0,
		propertiesAlias: 'Associate-经理券',
	},
	{
		cost: 0,
		color: 'SP-高级合伙人券',
		propertiesName: 'SP-高级合伙人券',
		agentPrice: 0,
		supplierSkucode: '',
		remainNum: 10000,
		picPath: '',
		stdSalePrice: 0,
		propertiesAlias: 'Associate-经理券',
	},
	{
		cost: 0,
		color: 'VP-副总裁券',
		propertiesName: 'VP-副总裁券',
		agentPrice: 0,
		supplierSkucode: '',
		remainNum: 10000,
		picPath: '',
		stdSalePrice: 0,
		propertiesAlias: 'Associate-经理券',
	},
];
